version: '3.8'
services:
  mysql:
    image: mysql:8.3
    platform: linux/arm64/v8
    command: "mysqld --character-set-server=utf8mb4"
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - "4301:3306"
  redis-cluster:
    image: grokzen/redis-cluster:7.0.10
    platform: linux/amd64
    environment:
      IP: '127.0.0.1'
      INITIAL_PORT: 4311
    ports:
      - '4311-4313:4311-4313'