logging:
  level:
    org.springframework.web.servlet: info
    org.springframework.boot.actuate: off
    org.springframework.web: debug
    org.springframework.boot: info
    org.straycats: debug

server:
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 4300

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    tagsSorter: alpha

app:
  client:
    naver:
      host: https://openapi.naver.com
      auth-host: https://nid.naver.com
      client-id: ''
      client-secret: ''
    kakao:
      host: https://kapi.kakao.com
      auth-host: https://kauth.kakao.com
      client-id: ''
      client-secret: ''
    apple:
      host: https://appleid.apple.com
      client-id: ''
      developer-team-id: ''
      developer-key-id: ''
      client-secret-public-key: ''
      client-secret-private-key: ''
    google:
      host: https://oauth2.googleapis.com
      client-id: ''
      client-secret: ''
